Rahul/Rishab - Final Setup What changes have you made? * Modify Readme.md file * Modify pre commit hooks and delete pre push hooks * delete .npmrc, private directory * Modify setup.sh and tools.sh * Add package-lock.json
Why do we need this change?
*For setting up the working environment

What can this change impact?
* Starting work is now much more easy

diff --git a/.github/pre_commit_hooks b/.github/pre_commit_hooks
--- a/.github/pre_commit_hooks
+++ b/.github/pre_commit_hooks
@@ -1,8 +1,30 @@
-set -xe
+#! /bin/sh
 
-echo "Running tests"
-npm test 
-echo "testing completed"
+RED="\033[0;31m"
+RESET="\033[0m"
+
+echo "Running test"
+npm run test 
+if [ "$?" -ne 0 ]; then
+  echo "${RED} ***** FAILING TESTS ***** ${RESET}" 
+  exit 1
+fi
+
+echo "Running coverage"
+npm run coverage
 
 echo "Checking coverage threshold"
-nyc check-coverage --lines 70
+nyc check-coverage 
+if [ "$?" -ne 0 ]; then
+  echo "${RED} ***** COVERAGE BELOW 90% ***** ${RESET}"
+  exit 1
+fi
+
+echo "Running linter"
+npm run lint
+if [ "$?" -ne 0 ]; then
+  echo "${RED} ***** LINTING ERRORS ***** ${RESET}"
+  exit 1
+fi
+
+exit 0
